### ISSUE TITLE
Push notification error

### ISSUE THREAD

**Issue by mpagnanelli** [BIDMCDigitalPsychiatry/LAMP-platform#116]
Hi,
I had below error
can you help me?
```
  (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:6379
```
i tried to load new configuration from documentation with no success. When i enable schedule this error block the lamp container.
here my configuration

```yaml
 version: '3.7'
services:
  server:
    image: 'lamp-server:latest'
    environment:
     - HTTPS=off
     - CDB=
     - DB_KEY=
     - ROOT_KEY=
     - SCHEDULER=on
     - PUSH_API_GATEWAY='
     - PUSH_API_KEY=''
     - REDIS_HOST= 'redis://cache:6379/0'
     - NATS_SERVER= 'message_queue:4222'
    networks:
      - public
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_server.entryPoints: 'websecure'
        traefik.http.routers.lamp_server.rule: 'Host(`thinksharpapi.angelinipharma.com`)'
        traefik.http.routers.lamp_server.tls.certresolver: 'default'
        traefik.http.services.lamp_server.loadbalancer.server.port: 3000
      placement:
        constraints:
          - node.role == manager
  database:
    image: apache/couchdb:latest
    volumes:
      - /home/ec2-user/data/couchdb:/opt/couchdb/data
    networks:
      - public
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_db.entryPoints: 'websecure'
        traefik.http.routers.lamp_db.rule: 'Host(`thinksharpdb.angelinipharma.com`)'
        traefik.http.routers.lamp_db.tls.certresolver: 'default'
        traefik.http.services.lamp_db.loadbalancer.server.port: 5984
      placement:
        constraints:
          - node.role == manager
  app-gateway:
    image: 'bidmcdigitalpsychiatry/lamp-app-gateway:latest'
    environment:
      APNS_P8: ""
      APNS_AUTH: ""
      API_KEYS: ""
    networks:
      - public
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_app_gateway.entryPoints: 'web'
        traefik.http.routers.lamp_app_gateway.rule: 'Host(`app-gateway.webhop.net`)'
        traefik.http.services.lamp_app_gateway.loadbalancer.server.port: 3000
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
networks:
  public:
    external: true
volumes:
  database:
  legacydb:
```

**Comment by jeydude1** [comment]
Here is my lamp configuration file

---------------------------------------------
version: '3.7'
services:
  server:
    image: bidmcdigitalpsychiatry/lamp-server:2021
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    environment:
      HTTPS: 'off'
      SCHEDULER: 'on'
      ROOT_KEY: 'YOURROOTKEY'
      CDB: 'http://admin:YOURPASSWORD@database:5984/'
      PUSH_API_GATEWAY: 'app-gateway.lamp.digital'
      PUSH_API_KEY: 'YOURPUSHKEY'
      DASHBOARD_URL: 'dashboard.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      NATS_SERVER: 'message_queue:4222'
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      labels:
         traefik.enable: 'true'
         traefik.http.routers.lamp_server.entryPoints: 'websecure'
         traefik.http.routers.lamp_server.rule: 'Host(`YOURHOSTNAME`)'
         traefik.http.routers.lamp_server.tls.certresolver: 'default'
         traefik.http.services.lamp_server.loadbalancer.server.port: 3000
      placement:
        constraints:
          - node.role == manager 
  database:
    image: mlpcouchdb
    healthcheck:
      test: curl --fail --silent http://localhost:5984/_up || exit 1
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: 'YOURPASSWORD'
    volumes:
      - /apps/mindLAMP/data/couchdb:/opt/couchdb/data
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
    ports:
    - "4369:4369/tcp"
    - "5984:5984/tcp"
    - "9100:9100/tcp"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.lamp_database.entryPoints: 'websecure'
      traefik.http.routers.lamp_database.rule: 'Host(`YOURDBHOSTNAME`)'
      traefik.http.routers.lamp_database.tls.certresolver: 'default'
      traefik.http.services.lamp_database.loadbalancer.server.port: 5984
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
networks:
  public:
    external: true
---------------------------------------------


Once I enabled the scheduler then I am getting following error and LAMP API container never goes to healthy mode.

**Here is the error log**
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)


(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
   at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
   at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)


(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)


(node:1) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
   at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/redis/index.js:285:37)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)

ActivitySpec database online.
SensorSpec database online.
Researcher database online.
Study database online.
Participant database online.
Activity database online.
Sensor database online.
ActivityEvent database online.
SensorEvent database online.
Credential database online.
Tag database online.
Database verification complete.
Server routing initialized.
Clean all queues…
CLEANING ALL QUEUE
(node:1) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN cache
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see Command-line options | Node.js v15.8.0 Documentation). (rejection id: 15)

**Comment by jeydude1** [comment]
Once the customer enabled Private network to enable push notification to work with LAMP API Server (https://mindlamp.discourse.group/t/unable-to-receive-push-notifications/231/19) do we need to have Private network? How to configure the Private network?

**Comment by avaidyam** [comment]
@mpagnanelli @jeydude1 Please update your `docker-compose.yml` to add the following in the `services` → `server` section: 
```yaml
    networks:
      - default
      - public
```

The `default` network is the internal private network auto-created by Docker Swarm. The `public` network must be created ahead of time for use with `traefik` (external access routing).

**Comment by jeydude1** [comment]
Thank you Aditya, That worked. After I have added **default** to LAMP API Server network list, push notification scheduler started.

Here is my LAMP API Server log after I have added default network and redeployed the mindLAMP stacks in portainer.

Initializing LAMP API server...
  Initializing database connection...
    Connected to Nats Pub Server
    Connected to Nats Sub Server
    ActivitySpec database online.
    SensorSpec database online.
    Researcher database online.
    Study database online.
    Participant database online.
    Activity database online.
    Sensor database online.
    ActivityEvent database online.
    SensorEvent database online.
    Credential database online.
    Tag database online.
  Database verification complete.
  Server routing initialized.
  Clean all queues...
  CLEANING ALL QUEUE
  DONE--CLEANING ALL QUEUE
  Initializing schedulers...
Initialization complete.
activity_id given undefined
Saving to redis
Processing 29 activities for push notifications.
locked job on activity_scheduler
actvityId wqcszngqgawy6exm35h2
participantslength 3
actvityId xgkpc0q2wb9jk06cfdxf
actvityId f8emztwhnxqeyrak835b
actvityId h2x1sm5y4hrys6p321df
actvityId 26szk8cttcbsv9ngnec5
actvityId qw774h2mm2e5j88cg58d
actvityId cq3b1p6pqgrtzkdpt416
actvityId kgpvyzbj098zyevz78bv
actvityId 2vhcsxak8v88vj8t0rcb
actvityId 6pzj92q6ccaw8741wsts
actvityId t9ghgn8hn91c34wtp606
actvityId gmr8jv48ce8ve7mkdbsd
actvityId 8amhwenggvx013w37vy5
actvityId mk8bfw38sghm7ng92fkc
actvityId xdcbckh2bzb0tjrm9k33
actvityId xw07pgy2257a8m0dd4h5
actvityId s9wjamynp0kyfd9fef29
actvityId 4gjfjbjpekjnyce41cqa
actvityId bfx54bdsf6fgp7kfdyrs
participantslength 1
actvityId 472cf23t24eb32yj0nbx
participantslength 1
actvityId 7zfymq54wncnzstk2f53
participantslength 2
actvityId 6w6ejdmjxhzs2wm6b5bp
actvityId y8rksht24gsjdf43aydt
actvityId a1sfhvgppr2m593qhsj0
participantslength 1
actvityId khp9tv894k2ew5fg3ydb
participantslength 1
actvityId 46m9vtdwdzc5sdxm5b49
participantslength 3
actvityId 67vgt8869j6rm3saqewh
actvityId msv3g9p4n3by8fk77tds
actvityId 6h1d9as9jz6c7acayhm1
Saving to Redis completed....
release lock  on success  activity_scheduler
GET / 200 - 15.835 ms

**Comment by avaidyam** [comment]
@jeydude1 It looks like your issue has been resolved -- @mpagnanelli you may need to do the same thing and you should be all set then as well!

**Comment by jeydude1** [comment]
Aditya, now I am getting Bad Gateway while trying to access https://<API URL>

**Comment by avaidyam** [comment]
Hmm, @jeydude1, could you try adding this line to the `services` → `server` → `deploy` → `labels` section?

```yaml
        traefik.docker.network: 'public'
```

**Comment by jeydude1** [comment]
THANKS A LOT! now the API server URL is working. Appreciate much! Looking forward to see the push notification messages. Thanks!


services:
  server:
    image: bidmcdigitalpsychiatry/lamp-server:2021
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    environment:
      HTTPS: 'off'
      SCHEDULER: 'on'
      ROOT_KEY: ''
      CDB: ''
      PUSH_API_GATEWAY: 'app-gateway.lamp.digital'
      PUSH_API_KEY: ''
      DASHBOARD_URL: 'dashboard.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      NATS_SERVER: 'message_queue:4222'
    networks:
      **- default**
      - public
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      labels:
         traefik.enable: 'true'
         traefik.http.routers.lamp_server.entryPoints: 'websecure'
         traefik.http.routers.lamp_server.rule: 'Host(`romlptestapi.mayo.edu`)'
         traefik.http.routers.lamp_server.tls.certresolver: 'default'
         traefik.http.services.lamp_server.loadbalancer.server.port: 3000
         **traefik.docker.network: 'public'**
      placement:
        constraints:
          - node.role == manager

**Comment by avaidyam** [comment]
That's great, @jeydude1! If you have any suggestions or improvements down the road, the docker stack file lives here in this repository so you can always send us a pull request.

**Comment by jeydude1** [comment]
Sure will do. Thanks!

**Comment by mpagnanelli** [comment]
Hi @avaidyam,
I keep getting the same error even when inserting
 networks:
     - default
 in server section.
here my configuration

version: '3.7'
services:
  server:
    image: 'bidmcdigitalpsychiatry/lamp-server:2021'
    environment:
     - HTTPS=off
     - CDB=
     - DB_KEY=
     - ROOT_KEY=
     - SCHEDULER=on
     - PUSH_API_GATEWAY=
     - PUSH_API_KEY=''
     - REDIS_HOST= 'redis://cache:6379/0'
     - NATS_SERVER= 'message_queue:4222'
    networks:
      - default
      - public
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_server.entryPoints: 'websecure'
        traefik.http.routers.lamp_server.rule: 'Host(`thinksharpapi.angelinipharma.com`)'
        traefik.http.routers.lamp_server.tls.certresolver: 'default'
        traefik.http.services.lamp_server.loadbalancer.server.port: 3000
      placement:
        constraints:
          - node.role == manager
  database:
    image: apache/couchdb:latest
    volumes:
      - /home/ec2-user/data/couchdb:/opt/couchdb/data
    networks:
      - public
    environment:
      - COUCHDB_USER=sa
      - COUCHDB_PASSWORD=Alecsandria01
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_db.entryPoints: 'websecure'
        traefik.http.routers.lamp_db.rule: 'Host(`thinksharpdb.angelinipharma.com`)'
        traefik.http.routers.lamp_db.tls.certresolver: 'default'
        traefik.http.services.lamp_db.loadbalancer.server.port: 5984
      placement:
        constraints:
          - node.role == manager
  app-gateway:
    image: 'bidmcdigitalpsychiatry/lamp-app-gateway:latest'
    environment:
      APNS_P8: "UZ7MLQHU53_it.angelini.alecsandria-thinksharp_KFSY8K97V9.p8"
      APNS_AUTH: "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgi+rm7JqHXAg1Qt+Aev7VYwYGQW6TVlymKm2fPrSNUhSgCgYIKoZIzj0DAQehRANCAAQdcj/i2cssWrhF+ctmPEAmS+4u011IUzU294iAUiZM9ihA1cwxnoh3JAWm06FWNPnQf4p0T4Ijp2UtNHFsPW9Q"
      GCM_AUTH: "AAAA8ppYWrQ:APA91bEeDDH1Ll-OqD_NbrBTx26XoVzxftJVggmmpioSpEk9ZD4S8eJ5CmmwqJ6pszdnBhG39OTQknil7amw2gK4U-qf87t8Aj6-D7Y7KLAhwhX7RcJkSX5RLISiMKB4EVjNatFEWsD_"
      API_KEYS: "n1WHtGTpRByGjeOP"
    networks:
      - public
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_app_gateway.entryPoints: 'web'
        traefik.http.routers.lamp_app_gateway.rule: 'Host(`app-gateway.webhop.net`)'
        traefik.http.services.lamp_app_gateway.loadbalancer.server.port: 3000
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
networks:
  public:
    external: true
volumes:
  database:
  legacydb:

**Comment by avaidyam** [comment]
1. For `redis` you should not need to declare `ports: - "6379:6379"` as all ports are accessible to containers on the same docker network. 
1. If you are not using `traefik`, then you should be able to remove the `labels` section containing `traefik.*` specific labels. 
1. You likely do **NOT** want your database on the `public` network. **(!)**
1. You may need to rename `PUSH_API_GATEWAY` to `APP_GATEWAY` (See #87 .) and ensure that you are directing it correctly to your own app gateway **via HTTPS and not HTTP**.

Let me know if these suggestions resolve the issue for you.

**Comment by mpagnanelli** [comment]
Hi @avaidyam 
1. i tried with and whitout port definition but the error persist.
2. i use traefik.
3. i enable public network on database to check the saved data for development purpose.
4. i tried alse with APP_GATEWAY with no success, HTTPS was enabled correctly.

here my last configuration

```
version: '3.7'
services:
  server:
    image: 'lamp-server:latest'
    environment:
     - HTTPS=off
     - CDB=
     - DB_KEY=
     - ROOT_KEY=
     - SCHEDULER=on
     - APP_GATEWAY='https://MY_APP GATEWAY'
     - PUSH_API_KEY=''
     - REDIS_HOST= 'redis://cache:6379/0'
     - NATS_SERVER= 'message_queue:4222'
    networks:
      - default
      - public
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_server.entryPoints: 'websecure'
        traefik.http.routers.lamp_server.rule: 'Host(`MYAPI`)'
        traefik.http.services.lamp_server.loadbalancer.server.port: 3000
        traefik.http.routers.lamp_server.tls.certresolver: 'default'
        traefik.docker.network: 'public'
      placement:
        constraints:
          - node.role == manager
  database:
    image: apache/couchdb:latest
    volumes:
      - /home/ec2-user/data/couchdb:/opt/couchdb/data
    networks:
      - public
    environment:
      - COUCHDB_USER=sa
      - COUCHDB_PASSWORD=Alecsandria01
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_db.entryPoints: 'websecure'
        traefik.http.routers.lamp_db.rule: 'Host(`MYDB`)'
        traefik.http.routers.lamp_db.tls.certresolver: 'default'
        traefik.http.services.lamp_db.loadbalancer.server.port: 5984
      placement:
        constraints:
          - node.role == manager
  app-gateway:
    image: 'bidmcdigitalpsychiatry/lamp-app-gateway:latest'
    environment:
      APNS_P8: ""
      APNS_AUTH: ""
      GCM_AUTH: ""
      API_KEYS: ""
    networks:
      - public
    deploy:
      mode: replicated
      labels:
        traefik.enable: 'true'
        traefik.http.routers.lamp_app_gateway.entryPoints: 'websecure'
        traefik.http.routers.lamp_app_gateway.rule: 'Host(`MY_APP GATEWAY`)'
        traefik.http.services.lamp_app_gateway.loadbalancer.server.port: 3000
        traefik.http.routers.lamp_app_gateway.tls.certresolver: 'default'
      placement:
        constraints:
          - node.role == manager
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
networks:
  public:
    external: true
volumes:
  database:
  legacydb:
```
