### ISSUE TITLE
Activity schedule API overhaul

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-platform#269]
The current `Activity.schedule` API component is fairly restrictive in the types of schedules that can be created for activities. The suggestion below allows a far greater degree of flexibility, including support for CRON expressions and push notification expiry limits (which are already implemented by the backend, but not exposed in the API). 

```yaml
schedule:
  type: array
  items: 
    type: object
    properties:
      start:
        type: DateTime
        required: false
        description: The date-time after which the schedule begins firing.
      end:
        type: DateTime
        required: false
        description: The date-time after which the schedule stops firing.
      repeat:
        type: CRONString
        required: true
        description: The CRON expression defining the repeat interval on which the schedule fires.
      expiry:
        type: TimeInterval
        required: false
        description: The amount of time before a push notification delivered for this schedule expires and is hidden.
```

This would also require a level of backwards compatibility (i.e. being able to convert the legacy schedule types to "modern" ones) and a new frontend interface for scheduling via CRON expressions.
