### ISSUE TITLE
Not able to disable sensor event cache or force it to flush to database periodically

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#489]
Hi,

Recently I updated my lamp api server on my test server to refer

```
image: ghcr.io/bidmcdigitalpsychiatry/lamp-server:2022
```

from
```
    image: bidmcdigitalpsychiatry/lamp-server:2021
```

after the image updated to 2022, I am not getting any sensor data to LAMP API Server. I could see my activity data, no issues.

Closed the iPhone app and reopened the iPhone few time still having issues to send sensor data to LAMP API server.

Here is the list of sensors and its settings applied now:
```
{
"data": [
  {
"id": "a0dhh5wty34th4n17cew",
"timestamp": 1616532925174,
"spec": "lamp.analytics",
"name": "analytics",
"settings": {}
},
  {
"id": "mqppvpn4qwqmx1bx8wdm",
"timestamp": 1616532945282,
"spec": "lamp.heart_rate",
"name": "HR",
"settings": {}
},
  {
"id": "aqfb40nrnr5n035gqfqq",
"timestamp": 1616532964156,
"spec": "lamp.screen_state",
"name": "Screen Status",
"settings": {}
},
  {
"id": "mc4f1yd4sf3yvt4w4e2a",
"timestamp": 1616532970516,
"spec": "lamp.sleep",
"name": "Sleep",
"settings": {}
},
  {
"id": "t928ka5nc4fv9g60r0wp",
"timestamp": 1616532976301,
"spec": "lamp.steps",
"name": "steps",
"settings": {}
},
  {
"id": "wvcarrj57jedaje8sa2x",
"timestamp": 1616532981861,
"spec": "lamp.telephony",
"name": "calls",
"settings": {}
},
  {
"id": "3ewpt11q4y656pgwxj8j",
"timestamp": 1623077614569,
"spec": "lamp.accelerometer",
"name": "Accelerometer",
"settings": {
"frequency": 0.0166,
"cellular_upload": true
}
},
  {
"id": "5pb6j7e88amnvwrzph72",
"timestamp": 1623077622389,
"spec": "lamp.gps",
"name": "GPS",
"settings": {
"frequency": 0.0166,
"cellular_upload": true
}
}
],
}
```

**Comment by avaidyam** [comment]
@jeydude Can you share your whole `docker-compose.yml` file? It's likely that NATS and Redis are not properly configured.

**Comment by jeydude** [comment]
here is the lamp stack yml file

```
version: '3.7'
services:
  server:
    image: bidmcdigitalpsychiatry/lamp-server:2021
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    environment:
      HTTPS: 'off'
      SCHEDULER: 'on'
      ROOT_KEY: 'fd804de0e9fb5bec33e888ad27c0ede41d39ff8e520c8a38fd8515618064ce24'
      CDB: 'http://admin:xxxxxx@database:5984/'
      APP_GATEWAY: 'app-gateway.lamp.digital'
      PUSH_API_KEY: 'gNfMiKQsCRAk42YB'
      DASHBOARD_URL: 'dashboard.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      NATS_SERVER: 'message_queue:4222'
    networks:
      - default
      - public
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      labels:
         traefik.enable: 'true'
         traefik.http.routers.lamp_server.entryPoints: 'websecure'
         traefik.http.routers.lamp_server.rule: 'Host(`xxxxxx`)'
         traefik.http.routers.lamp_server.tls.certresolver: 'default'
         traefik.http.services.lamp_server.loadbalancer.server.port: 3000
         traefik.docker.network: 'public'
      placement:
        constraints:
          - node.role == manager 
  database:
    image: mlpcouchdb
    healthcheck:
      test: curl --fail --silent http://localhost:5984/_up || exit 1
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: 'xxxxxx'
    volumes:
      - /apps/mindLAMP/data/couchdb:/opt/couchdb/data
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
    ports:
    - "4369:4369/tcp"
    - "5984:5984/tcp"
    - "9100:9100/tcp"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.lamp_database.entryPoints: 'websecure'
      traefik.http.routers.lamp_database.rule: 'Host(`xxxxxxxx`)'
      traefik.http.routers.lamp_database.tls.certresolver: 'default'
      traefik.http.services.lamp_database.loadbalancer.server.port: 5984
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
networks:
  public:
    external: true
```

**Comment by avaidyam** [comment]
@jeydude Could you also share system logs from the `server`?

**Comment by jeydude** [comment]
Initial log file after i changed to 2022, I will send the another log file in another 10 minutes 
[_lamp_server.1.t2p9d6ih14azixkkgk29e6qdj_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7975237/_lamp_server.1.t2p9d6ih14azixkkgk29e6qdj_logs.txt)

**Comment by avaidyam** [comment]
@jeydude Are you suggesting the data is not in the database after 10 minutes? If that's the case - the reason this behavior occurs is the server actually caches sensor data before writing to the database in bulk. You may need to wait longer or collect more sensor data first.

**Comment by jeydude** [comment]
@avaidyam, no I am not suggesting data is not in the database, as you know, iPhone sends data every 10 minutes to the LAMP API server, so I have to wait for 10 minutes to see if there is any POST log, that's all.

I had the iPhone app up and running during in foreground during this test:
[_lamp_server.1.t2p9d6ih14azixkkgk29e6qdj_logs (2).txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7975251/_lamp_server.1.t2p9d6ih14azixkkgk29e6qdj_logs.2.txt)

**Comment by avaidyam** [comment]
Can you check in Redis to see if the data is being cached? It won't show up in the database until the cache is full and is flushed from Redis to the database.

**Comment by jeydude** [comment]
How do I check that. Sorry I am very bad with Redis

**Comment by avaidyam** [comment]
[Try this.](https://stackoverflow.com/questions/14844672/how-do-i-view-my-redis-database-current-size) You should be able to see increasing memory usage until the data is flushed, then the memory usage should drop.

**Comment by jeydude** [comment]
bash-4.4$ redis-cli info memory
bash: redis-cli: command not found
bash-4.4$ which redis-cli
which: no redis-cli in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)

**Comment by jeydude** [comment]
Uploading log file from lamp_cache

[_lamp_cache.1.j8to4gcqhyywq8n9k3sj00ieb_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7975323/_lamp_cache.1.j8to4gcqhyywq8n9k3sj00ieb_logs.txt)

**Comment by jeydude** [comment]
memory and cache seems to be same level
![image](https://user-images.githubusercontent.com/841011/151901319-85ff0a95-2e48-4ce1-bfdd-6f19afd65796.png)

**Comment by jeydude** [comment]
I will check with unix admin for redis command to check the memory, if there is anything you need let me know, for now I am going to put it back to 2021 image.

**Comment by jeydude** [comment]
After switching back to 2021 image, sensor data is coming fine to couchdb, no issues.

Initial log file of 2021 image
[_lamp_server.1.7oifpvvyx88itwst0lrhaomqx_logs (1).txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7975414/_lamp_server.1.7oifpvvyx88itwst0lrhaomqx_logs.1.txt)
![image](https://user-images.githubusercontent.com/841011/151903594-aa476a27-8c04-485c-bf17-9b0b8d77dfb1.png)

after 10 minutes of 2021 image logs file
[_lamp_server.1.7oifpvvyx88itwst0lrhaomqx_logs.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/7975415/_lamp_server.1.7oifpvvyx88itwst0lrhaomqx_logs.txt)
![image](https://user-images.githubusercontent.com/841011/151903656-7ee10793-d393-4ee8-aad5-048b98919ce9.png)

Anyone reported issues with sensor data collection using 2022 image?

**Comment by avaidyam** [comment]
@jeydude No, and there shouldn't be any difference as the 2022 server release doesn't actually change code for sensor data collection at all.

**Comment by avaidyam** [comment]
There should not be any OpenAPI change. We'll get back to you on next steps for resolving this issue shortly!

**Comment by jeydude** [comment]
Thanks a lot for your support!

**Comment by jeydude** [comment]
Here is the output of the Redis memory 

bash-4.4$ docker exec lamp_cache.1.j8to4gcqhyywq8n9k3sj00ieb redis-cli info memory
# Memory
used_memory:1243760
used_memory_human:1.19M
used_memory_rss:6332416
used_memory_rss_human:6.04M
used_memory_peak:2614488
used_memory_peak_human:2.49M
used_memory_peak_perc:47.57%
used_memory_overhead:1052722
used_memory_startup:802984
used_memory_dataset:191038
used_memory_dataset_perc:43.34%
allocator_allocated:1237400
allocator_active:1724416
allocator_resident:4431872
total_system_memory:8118042624
total_system_memory_human:7.56G
used_memory_lua:80896
used_memory_lua_human:79.00K
used_memory_scripts:27024
used_memory_scripts_human:26.39K
number_of_cached_scripts:10
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.39
allocator_frag_bytes:487016
allocator_rss_ratio:2.57
allocator_rss_bytes:2707456
rss_overhead_ratio:1.43
rss_overhead_bytes:1900544
mem_fragmentation_ratio:5.36
mem_fragmentation_bytes:5150656
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:220818
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
bash-4.4$

**Comment by avaidyam** [comment]
@jeydude Do you know specifically which version of the `LAMP-server` you're using? Normally the `2021` label is an alias for something like `2021.3.14` or `2021.10.11` or so.

**Comment by jeydude** [comment]
Looks like it was created 9 months ago - https://hub.docker.com/r/bidmcdigitalpsychiatry/lamp-server/tags

![image](https://user-images.githubusercontent.com/841011/152382758-dd36543d-d091-4c43-a29d-3232bcc2597f.png)

**Comment by avaidyam** [comment]
That seems to be an incredibly out of date version of the server. Let me investigate what could have changed. Just to confirm - are you also using the `LAMP-worker` component?

**Comment by jeydude** [comment]
No, we are not using LAMP-worker component. I have following containers LAMP Server, LAMP database (couchdb), LAMP Cache (Redis) LAMP message (Nats) deployed in our box.

**Comment by avaidyam** [comment]
Understood -- for now, please keep using that version of the server. I'll work with our team to identify the issue and update documentation. I'll keep you posted here!

**Comment by jeydude** [comment]
Thanks a lot!

**Comment by jeydude** [comment]
Hi Aditya, any update?

I tried to use 
```
ghcr.io/bidmcdigitalpsychiatry/lamp-server:2021.9.13
```

In the log file, I have noticed Store Size is increasing, but it is not pushed to CouchDB yet. Do I need to wait for Store_Size to reach Max_Store_Size to see the data in CouchDB? Is there a way to reduce the Max_Store_Size?

2022-02-09T17:30:41.904897002Z POST /participant/U2932822766/sensor_event 200 - 14.185 ms

2022-02-09T17:30:41.904909817Z Store_Size 402

2022-02-09T17:30:41.904912991Z Max_Store_Size 50000

2022-02-09T17:30:41.904915691Z Inserting data to redis store

2022-02-09T17:30:42.029921895Z POST /participant/U2932822766/sensor_event 200 - 6.606 ms

2022-02-09T17:30:42.030403309Z Store_Size 412

2022-02-09T17:30:42.030415116Z Max_Store_Size 50000

2022-02-09T17:30:42.030418483Z Inserting data to redis store

**Comment by avaidyam** [comment]
@jeydude Are you able to see similar logs regarding `Store_Size` and `Max_Store_Size` in the `:2022` release? 

If not, this may be the issue - the store size (number of events to cache before flushing to database) should be configurable and it is currently not. I imagine `store_size=0` disables it, and `store_size=100` would set a small enough size that you would see real-time updates on your data tracker. 

Do you think that covers your needs?

**Comment by jeydude** [comment]
@avaidyam 

I tried the ```2022 ``` release and ```latest``` release, both does not show the Store_Size and Max_Store_Size in the logs. Looking at the source code, looks like you guys have removed those log entries in around 2022 release.

I am assuming I need to apply store_size=100 to environment section and once I applied it, I will let you know if I am getting sensor_events data or not. Thanks for your response.

```
    environment:
      HTTPS: 'off'
      SCHEDULER: 'on'
      ROOT_KEY: 'xxxxxxx'
      CDB: 'http://admin:xxxxxx@database:5984/'
      APP_GATEWAY: 'app-gateway.lamp.digital'
      PUSH_API_KEY: 'xxxxxxx'
      DASHBOARD_URL: 'dashboard.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      NATS_SERVER: 'message_queue:4222'
      store_size:100
```
