### ISSUE TITLE
while adding LAMP worker to the stack list getting error

### ISSUE THREAD

**Issue by jeydude** [BIDMCDigitalPsychiatry/LAMP-platform#562]
I have added below LAMP worker component to my LAMP stack in **production** environment
```
worker:
    image: ghcr.io/bidmcdigitalpsychiatry/lamp-worker:2022
    environment:
      DASHBOARD_URL: 'dashboard.lamp.digital'
      PORT: '3000'
      NATS_SERVER: 'message_queue:4222'
      APP_GATEWAY: 'app-gateway.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      PUSH_API_KEY: 'YOUR_API_KEY_HERE'
      DOCKER_ADDR: '127.0.0.1:2375'
      LAMP_SERVER: 'YOUR_API SERVER_DOMAIN_HERE'
      LAMP_AUTH: 'ADMIN_USERNAME:ADMIN_PASSWORD'
      TIMEZONE: 'America/New_York'
      SCHEDULER: 'on'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - public
```
after i start the stack in portainer. I am getting below error in worker-component container log:
```
FetchError: request to https://SERVER_DOMAIN_HERE/researcher failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}

```

To avoid this error, I have added 

```NODE_TLS_REJECT_UNAUTHORIZED: 0 ```

which took care of the issue, but I was told, i should not add  NODE_TLS_REJECT_UNAUTHORIZED: 0 in production environment, what needs to be done in in production environment to avoid this error?
