### ISSUE TITLE
Deploying LAMP-activites to Staging and Production

### ISSUE THREAD

**Issue by MattMatt27** [BIDMCDigitalPsychiatry/LAMP-platform#881]
@ZCOEngineer @sarithapillai8

Hi there! @willscripted and I have been working on deploying the `LAMP-dashboard` to new containers running in ECS as opposed to EC2. As part of those deployments we have been running into trouble pointing at the correct `LAMP-activities` branch. 

Can you provide a bit more background on how the LAMP-activities repository works? How would we build a container that uses staging activities, vs how would we build a container with production ready activities? Would it be possible to update [buildEnv.js](https://github.com/BIDMCDigitalPsychiatry/LAMP-dashboard/blob/b6a97ae499bd027e6f4e673d780f7fab2296f2c7/buildEnv.js#L53-L57) to determine which activities are staging and production ready using some method other than the git history?

**Comment by sarithapillai8** [comment]
@MattMatt27 

We are currently using the below condition for uploading activities : 
 let activityURL = "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/"
 activityURL += process.env.REACT_APP_GIT_SHA === "dev" ? "dist/out" : "latest/out"

Can we use seperate static env file for staging and production?

**Comment by sarithapillai8** [comment]
@MattMatt27 

We are currently using the below condition for loading activities : 
 let activityURL = "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/"
 activityURL += process.env.REACT_APP_GIT_SHA === "dev" ? "dist/out" : "latest/out"

Can we use seperate static env file for staging and production?

**Comment by sarithapillai8** [comment]
@MattMatt27 
No need to change the LAMP-activities for production release. We can use the same release method of LAMP-activities as before using the latest tag. We can use separate env files for production and staging.

**Comment by MattMatt27** [comment]
@sarithapillai8 Historically has it been our team or yours responsible for releasing the `LAMP-activities` repo? I can see @ertjlane released the last latest version, but you also have a few releases as well. 

I ask because we are planning to release the last few months of dashboard changes on Thursday, and I think it would make sense to release the recent activities changes at the same time. If we are responsible on our side for releasing `LAMP-activities`, is the dist branch the one that we should be releasing, and is it ready to be released to production?

**Comment by sarithapillai8** [comment]
@MattMatt27 Yes. You team was responsible for the release.

**Comment by MattMatt27** [comment]
For my own understanding, how do we define what activities appear in staging vs production? 

In the staging dashboard built with the dist branch of activities (`https://lamp-dashboard.zcodemo.com`) there are a number of activities that we definitely do not want to appear in production. Some examples included in the screenshot below. 
<img width="253" alt="Image" src="https://github.com/user-attachments/assets/1ea2acdd-2289-44fa-b534-20d64736ea6d" />

These don't show up in production currently so I assume there is a place where we define what activities are approved for external users, but I am not quite familiar enough with the code to know where that is.

**Comment by willscripted** [comment]
So if I'm reading things right:

- the stable versions of activities are loaded directly from the `latest` git tag
- the `latest` git tag is determined by the most recent release that checks the "set as latest" checkbox
- development of activities is periodically pushed up to the `dist` _branch_
- the dashboard decides at build-time which of the two refs to reference

This allows us to:

- update activities without creating any new releases of ios, android, or dashboard
- pilot changes to activities by pushing them to the `dist` branch before publishing them as a release

**Comment by willscripted** [comment]
And when we publish the next version of dashboard, nothing should change from our existing configuration so long as we are referencing `latest` at build-time. We should be able to verify this in staging ahead of time.

**Comment by willscripted** [comment]
Does all this sound correct to you @sarithapillai8 ?

**Comment by MattMatt27** [comment]
How exactly to we make a release off of the dist branch? When I attempt to do so using the configuration below (pointing at the latest released tag `2024.5.10`, the Generated release notes show no pull requests since the last release, despite there being 95 new commits. 
<img width="1125" alt="Image" src="https://github.com/user-attachments/assets/80c87820-a3eb-46ba-bc88-b4c4e97602de" />

**Comment by sarithapillai8** [comment]
@MattMatt27 I am not sure how to specify those commits here. We are updating the master branch. dist branch gets updated automatically, so commits won't be there.  We were not used to release LAMP-activities with commits, so we didn't check that option. If you need we can check and let you know.

**Comment by MattMatt27** [comment]
@sarithapillai8 I recently made a release of the dist branch and the changes appear to have landed: https://github.com/BIDMCDigitalPsychiatry/LAMP-activities/releases/tag/2025.03.24

Looking through our notes it seems that in the past there have been steps your team needed to complete once we created a release, is this still the case?

**Comment by sarithapillai8** [comment]
@MattMatt27 We don’t need to take any action on our side. However, it looks like the latest tag did not point to the release you made. So, I have created a new release with the latest tag for now. Could you please check?

**Comment by MattMatt27** [comment]
This is a known issue with the CI/CD workflow. Making releases on the dist branch will update the latest flag in dist but not automatically update it on master. I am doing some exploration to see if it would make sense to  update out GitHub action to handle both latest flags, or if there is a reason to keep the process the same where your team has to update master after we release dist. No action needed on the Zco side for now, but I will leave this ticket open as I dig into the GitHub workflow actions. 

A potential update to `release.yml` that I am considering. This would theoretically solve the master tagging issue, but would leave the lack of release notes as a problem. 
```
name: Release
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name gh-actions
          git config --global user.email actions@github.com

      # Update the latest tag on dist
      - name: Tag dist branch
        run: |
          git checkout dist
          git tag -a -f latest -m 'latest release' ${{ github.ref_name }}
          git push --force origin latest

      # Create a corresponding tag on master
      - name: Tag master branch
        run: |
          git checkout master
          git tag -a -f latest-master -m 'latest master for release' HEAD
          git push --force origin latest-master
```
